/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.paad.earthquake;

public final class R {
    public static final class array {
        public static final int magnitude=0x7f040001;
        public static final int magnitude_options=0x7f040002;
        public static final int update_freq_options=0x7f040000;
        public static final int update_freq_values=0x7f040003;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int cancelButton=0x7f060006;
        public static final int checkbox_auto_update=0x7f060002;
        public static final int earthquakeListView=0x7f060001;
        public static final int map_view=0x7f060000;
        public static final int okButton=0x7f060005;
        public static final int quakeDetailsTextView=0x7f060007;
        public static final int spinner_quake_mag=0x7f060004;
        public static final int spinner_update_freq=0x7f060003;
    }
    public static final class layout {
        public static final int earthquake_map=0x7f030000;
        public static final int main=0x7f030001;
        public static final int preferences=0x7f030002;
        public static final int quake_details=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int auto_update_prompt=0x7f050003;
        public static final int menu_earthquake_map=0x7f050007;
        public static final int menu_preferences=0x7f050006;
        public static final int menu_update=0x7f050002;
        public static final int min_quake_mag_prompt=0x7f050005;
        public static final int quake_feed=0x7f050001;
        public static final int update_freq_prompt=0x7f050004;
    }
}
