/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.paad.emergencyresponder;

public final class R {
    public static final class array {
        public static final int respondForDisplayItems=0x7f040000;
        public static final int respondForValues=0x7f040001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int autoResponder=0x7f060009;
        public static final int buttonLayout=0x7f060006;
        public static final int cancelButton=0x7f060004;
        public static final int checkboxLocation=0x7f060001;
        public static final int checkboxSendLocation=0x7f060007;
        public static final int labelRequestList=0x7f060005;
        public static final int myListView=0x7f06000a;
        public static final int notOkButton=0x7f060008;
        public static final int okButton=0x7f060003;
        public static final int responseText=0x7f060000;
        public static final int spinnerRespondFor=0x7f060002;
    }
    public static final class layout {
        public static final int autoresponder=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int autoRespondPref=0x7f050009;
        public static final int includeLocationPref=0x7f050007;
        public static final int querystring=0x7f050005;
        public static final int respondAllClearButtonText=0x7f050001;
        public static final int respondAllClearText=0x7f050003;
        public static final int respondForPref=0x7f05000a;
        public static final int respondMaydayButtonText=0x7f050002;
        public static final int respondMaydayText=0x7f050004;
        public static final int responseTextPref=0x7f050008;
        public static final int user_preferences=0x7f050006;
    }
}
