/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.paad.todolist;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int notepad_lines=0x7f040001;
        public static final int notepad_margin=0x7f040002;
        public static final int notepad_paper=0x7f040000;
        public static final int notepad_text=0x7f040003;
    }
    public static final class dimen {
        public static final int notepad_margin=0x7f050000;
    }
    public static final class drawable {
        public static final int add_new_item=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int remove_item=0x7f020002;
    }
    public static final class id {
        public static final int myEditText=0x7f080000;
        public static final int myListView=0x7f080001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int todolist_item=0x7f030001;
    }
    public static final class string {
        public static final int add_new=0x7f060001;
        public static final int app_name=0x7f060000;
        public static final int cancel=0x7f060003;
        public static final int remove=0x7f060002;
    }
    public static final class style {
        public static final int ToDoTheme=0x7f070000;
    }
}
