/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.paad.contentslider;

public final class R {
    public static final class anim {
        public static final int slide_bottom_in=0x7f040000;
        public static final int slide_bottom_out=0x7f040001;
        public static final int slide_left_in=0x7f040002;
        public static final int slide_left_out=0x7f040003;
        public static final int slide_right_in=0x7f040004;
        public static final int slide_right_out=0x7f040005;
        public static final int slide_top_in=0x7f040006;
        public static final int slide_top_out=0x7f040007;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int myTextView=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int hello=0x7f050000;
    }
}
