/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.paad.chapter8;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int background_color=0x7f040000;
        public static final int marker_color=0x7f040001;
        public static final int text_color=0x7f040002;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int cardinal_east=0x7f050003;
        public static final int cardinal_north=0x7f050002;
        public static final int cardinal_south=0x7f050004;
        public static final int cardinal_west=0x7f050005;
        public static final int hello=0x7f050000;
    }
}
