/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.paad.chapter3;

public final class R {
    public static final class anim {
        public static final int spin_shrink_fade=0x7f040000;
    }
    public static final class array {
        public static final int countdown=0x7f080001;
        public static final int default_todo_items=0x7f080000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int app_background=0x7f050002;
        public static final int opaque_blue=0x7f050000;
        public static final int transparent_green=0x7f050001;
    }
    public static final class dimen {
        public static final int default_border=0x7f060002;
        public static final int large_font_size=0x7f060001;
        public static final int standard_border=0x7f060000;
    }
    public static final class drawable {
        public static final int fbf1=0x7f020000;
        public static final int fbf2=0x7f020001;
        public static final int fbf3=0x7f020002;
        public static final int frame_by_frame=0x7f020003;
        public static final int icon=0x7f020004;
    }
    public static final class id {
        public static final int myEditText=0x7f0a0000;
        public static final int myEditText2=0x7f0a0001;
        public static final int myEditText3=0x7f0a0002;
        public static final int myTextView=0x7f0a0003;
    }
    public static final class layout {
        public static final int ch3_res_test=0x7f030000;
        public static final int ch3_res_test_3=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int app_error=0x7f070005;
        public static final int app_name=0x7f070000;
        public static final int hello=0x7f070001;
        public static final int stop_message=0x7f070004;
        public static final int stop_message_0=0x7f070002;
        public static final int stop_message_1=0x7f070003;
    }
    public static final class style {
        public static final int BaseText=0x7f090000;
        public static final int SmallText=0x7f090001;
    }
}
